name: main
type: pass
steps:
  - name: rand
    type: function
    source: rand
    output:
      - rand_result
  - name: my_parallel
    type: parallel
    branches:
      - name: square
        type: function
        source: square
        output: 
          - square_result
        inputMappings:
          - target: x
            source: LOCAL.rand_result
      - name: cube
        type: function
        source: cube
        output: 
          - cube_result
        inputMappings:
          - target: x
            source: LOCAL.rand_result
  - name: add
    type: function
    source: add
    output:
      - add_result
    inputMappings:
      - target: x
        source: LOCAL.square_result
      - target: y
        source: LOCAL.cube_result
outputMappings:
  - target: result
    source: LOCAL.add_result

#   ------------> square  ------------|
#   |                                 ↓
#  rand                              add
#   |                                 ↑ 
#   |-----------> cube    ------------|

# Since we define outputMappings for `main`, 
# the final output will be {"result": ...}.